### ISSUE TITLE
https://demo.cozycloud.cc/apps/todos displays an error message

### ISSUE THREAD

**Issue by brouberol** [cozy/todos#45]
It's not exactly an issue with ``todos``, but  https://demo.cozycloud.cc/apps/todos display the following error message:

![screenshot from 2015-11-18 21-52-59](https://cloud.githubusercontent.com/assets/480131/11254067/23832110-8e3f-11e5-8f2d-77d9db9a4975.png)

**Comment by clochix** [comment]
Hi @brouberol, thanks for noticing (and sorry for my late reply).
This issue is related to our demo infrastructure : the demo is hosted on several load balanced server that are not synced. The Todo application is not installed by default, so you probably installed it by hand. But I guess next time you tried the demo, the load balancer sent your request to a server where the application is not installed, resulting to the error page you just saw.

So this is not an issue with this application, but with our demo infrastructure.

**Comment by brouberol** [comment]
Fair enough, thanks!
